version: 2.1
jobs:
    build:
        docker:
            - image: "mono"
        steps:
            - checkout
            - run:
                name: build
                command: chmod +x build.sh && ./build.sh
            - store_artifacts:
                path: makebin.exe
            - run:
                name: install python
                command: apt-get update && apt-get install python3 -y
            - run:
                name: run tests
                command: python3 tests.py

workflows:
    version: 2
    build-and-test:
        jobs:
            - build