version: 2.1
jobs:
    build:
        docker:
            - image: "mono"
        steps:
            - checkout
            - run:
                name: build
                command: chmod +x build.sh && ./build.sh
            - run:
                name: test
                command: chmod +x compile.sh && ./compile.sh

workflows:
    version: 2
    build-and-test:
        jobs:
            - build