name: "build and test"

on: ["push", "pull_request"]

jobs:
    build-compiler:
      runs-on: "ubuntu-latest"
      container: "mono"

      steps:
      - uses: "actions/checkout@v2"

      - name: "build"
        run: "./build.sh"
        working-directory: "makebin"

      - uses: "actions/upload-artifact@v2"
        with:
          name: "compiler"
          path: "makebin.exe"

      - uses: "actions/upload-artifact@v2"
        with:
          name: "compiler"
          path: "dnlib.dll"

    precompile-tests:
      runs-on: "ubuntu-latest"
      container: "python:3.7"

      steps:
      - uses: "actions/checkout@v2"

      - name: "precompile tests"
        run: "python3 precomptests.py"
        
      - uses: "actions/upload-artifact@v2"
        with:
          name: "precomp"
          path: "precompiled/"

    compile-run-tests:
      needs: ["build-compiler", "precompile-tests"]
      runs-on: "ubuntu-latest"
      container: "mono"

      steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/download-artifact@v2"
        with:
          name: "precomp"
          path: "./precompiled/"

      - uses: "actions/download-artifact@v2"
        with:
          name: "compiler"

      - name: "compile and run tests"
        run: "./runtests.sh"
