name: "build and test"

on: ["push"]

jobs:
    build-compiler:
      runs-on: "ubuntu-latest"
      container: "mono"

      steps:
      - uses: "actions/checkout@v2"

      - name: "build"
        run: "chmod +x build.sh && ./build.sh"

      - uses: "actions/upload-artifact@v2"
        with:
          name: "compiler"
          path: "makebin.exe"

    precompile-tests:
      runs-on: "ubuntu-latest"
      container: "python:3.7"

      steps:
      - uses: "actions/checkout@v2"

      - name: "run tests"
        run: "python3 tests.py"
        
      - uses: "actions/upload-artifact@v2"
        with:
          name: "precomp"
          path: "precompiled/"

    compile-run-tests:
      needs: ["build-compiler", precompile-tests]
      runs-on: "ubuntu-latest"
      container: "mono"

      steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/download-artifact@v2"
        with:
          name: "precomp"

      - name: "test"
        run: "ls -Rlh"